version: '3.3'

services:

  # Postgresql 11 shared DB
  PostgreSQL:
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - PGPORT=${DATABASE_PORT}
    image: postgres:11-alpine
    env_file: .env
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres:/var/lib/postgresql/${DATABASE_NAME}/data:rw
    healthcheck:
      test: [ "CMD", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5

  # OPA Server
  opa:
    image: openpolicyagent/opa:latest-rootless
    env_file: .env
    ports:
      - "${OPA_PORT}:${OPA_PORT}"
    command:
      - "run"
      - "--server"
      - "--log-level=${OPA_LOG_LEVEL}"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
    volumes:
      - opa:/var/lib/opa/data:rw

  # Policy service Spring boot app
  policyservice:
    depends_on:
      - opa
      - PostgreSQL
    build:
      context: odm-platform-up-services-policy-opa/
      args:
        SPRING_PROFILES_ACTIVE: "docker"
        DATABASE_URL: "jdbc:postgresql://PostgreSQL:${DATABASE_PORT}/${DATABASE_NAME}"
        DATABASE_USERNAME: "${DATABASE_USERNAME}"
        DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
        FLYWAY_SCHEMA: "ODMPOLICY"
        FLYWAY_SCRIPTS_DIR: "postgresql"
        SPRING_LOCAL_PORT: "${POLICYSERVICE_SPRING_PORT}"
        OPA_HOSTNAME: "opa"
        OPA_PORT: "${OPA_PORT}"
    env_file: .env
    ports:
      - "${POLICYSERVICE_SPRING_PORT}:${POLICYSERVICE_SPRING_PORT}"

  # Metaservice Spring Boot app
  metaservice:
    container_name: "odm-metaservice"
    depends_on:
      - PostgreSQL
    build:
      context: odm-platform-up-services-meta-blindata/
      args:
        SPRING_PROFILES_ACTIVE: "docker"
        SPRING_PORT: "${METASERVICE_SPRING_PORT}"
        JAVA_OPTS: ""
        DATABASE_URL: "jdbc:postgresql://PostgreSQL:${DATABASE_PORT}/${DATABASE_NAME}"
        DATABASE_USERNAME: "${DATABASE_USERNAME}"
        DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
        FLYWAY_SCHEMA: "ODMNOTIFICATION"
        FLYWAY_SCRIPTS_DIR: "postgresql"
        BLINDATA_URL: "${BLINDATA_URL}"
        BLINDATA_USER: "${BLINDATA_USER}"
        BLINDATA_PWD: "${BLINDATA_PWD}"
        BLINDATA_TENANT: "${BLINDATA_TENANT}"
        BLINDATA_ROLE: "${BLINDATA_ROLE}"
    env_file: .env
    ports:
      - "${METASERVICE_SPRING_PORT}:${METASERVICE_SPRING_PORT}"

  # Platform Spring Boot app
  platform:
    container_name: "odm-platform"
    depends_on:
      - PostgreSQL
      - metaservice
      - policyservice
    build:
      context: odm-platform-pp-services/
      args:
        SPRING_PROFILES_ACTIVE: "docker"
        SPRING_PORT: "${PLATFORM_SPRING_PORT}"
        JAVA_OPTS: ""
        DATABASE_URL: "jdbc:postgresql://PostgreSQL:${DATABASE_PORT}/${DATABASE_NAME}"
        DATABASE_USERNAME: "${DATABASE_USERNAME}"
        DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
        FLYWAY_SCHEMA: "ODMREGISTRY"
        FLYWAY_SCRIPTS_DIR: "postgresql"
        SKIP_METASERVICE: "false"
        METASERVICE_HOSTNAME: "metaservice"
        METASERVICE_PORT: "${METASERVICE_SPRING_PORT}"
        SKIP_POLICYSERVICE: "false"
        POLICYSERVICE_HOSTNAME: "policyservice"
        POLICYSERVICE_PORT: "${POLICYSERVICE_SPRING_PORT}"
    env_file: .env
    ports:
      - "${PLATFORM_SPRING_PORT}:${PLATFORM_SPRING_PORT}"

volumes:
  postgres:
  opa: